version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: faq
    networks:
      - faq-network

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - faq-network

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=redis://redis:6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - mongo
      - redis
    networks:
      - faq-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:5000/api
    depends_on:
      - server
    networks:
      - faq-network

networks:
  faq-network:

volumes:
  mongo-data:
  redis-data: